### PR TITLE
PR Greeting view controller

### PR DESCRIPTION
**Pull request by torsello**
## Summary
- Adding controller package
- Adding BookController
- Adding Greeting method
- Adding Greeting view

## Trello Card
https://trello.com/c/Zocum13Y

## Feature screenshot
https://i.imgur.com/ylzUyU8.png

### CODE REVIEW

**Review by julianvasquez-wolox — APPROVED** [review]
It looks good for me, good job!

PD: Those screenshots 👌🏼
PD2: I don't know why all the files from PR1 are still in this PR 🤔

**Comment by torsello** [comment]
> It looks good for me, good job!
> 
> PD: Those screenshots 👌🏼
> PD2: I don't know why all the files from PR1 are still in this PR

it may be because I started working from the base project branch, before the PR is approved?

**Review by zeminlu — APPROVED** [review]
LGTM!

**Review by zeminlu — CHANGES_REQUESTED** [review]
You didn't rebase this branch after merging the PR 1, do so and the extra files will disappear.

**Review by zeminlu — APPROVED** [review]

**Pull request merged**
